[package]
name = "flybywireless-xplm-macros"
version = "0.1.3"
description = "Procedural macros for flybywireless-xplm"
edition.workspace = true
authors.workspace = true
readme = "README.md"
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
